version: 2
jobs:

  build_backend:
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.6-alpine
        name: postgres
    environment:
      POSTGRES_PASSWORD: "pwd"
      DJANGO_ENVIRONMENT: "development"
      DJANGO_SECRET: "test-secret"
    working_directory: ~/repo/backend
    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: make migrations
          command: |
            sleep 2
            . venv/bin/activate
            python manage.py makemigrations
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_backend
