# Generated by Django 2.1.2 on 2018-12-04 19:01

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('google_uid', models.CharField(blank=True, max_length=200)),
                ('google_token', models.CharField(blank=True, max_length=2000)),
                ('facebook_uid', models.CharField(blank=True, max_length=200)),
                ('facebook_token', models.CharField(blank=True, max_length=500)),
                ('signup_complete', models.BooleanField(default=False)),
                ('notification_token', models.CharField(blank=True, max_length=100)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('position_timestamp', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=100)),
                ('distance_traveled', models.IntegerField(default=0)),
                ('blocked', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('goal', models.IntegerField()),
                ('reward', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Level'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
