# Generated by Django 2.1.2 on 2018-12-05 14:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
