# Generated by Django 2.1.2 on 2018-11-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181112_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='userLink',
            new_name='user',
        ),
    ]
