# Generated by Django 2.1.2 on 2018-11-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181112_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='facebook_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='facebook_uid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='google_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='google_uid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
