# Generated by Django 2.1.2 on 2018-12-05 15:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181205_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
