# Generated by Django 2.1.2 on 2018-12-15 14:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181205_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='position_history',
            field=models.ManyToManyField(blank=True, to='accounts.HistoricPosition'),
        ),
    ]
