# Generated by Django 2.1.2 on 2018-12-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181215_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicposition',
            name='altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
