# Generated by Django 2.1.2 on 2018-12-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_historicposition_altitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicposition',
            name='initial',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
