# Generated by Django 2.1.2 on 2018-11-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181112_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2011-09-01T13:20:30+03:00'),
            preserve_default=False,
        ),
    ]
