# Generated by Django 2.1.2 on 2018-11-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created',
        ),
    ]
