# Generated by Django 2.1.2 on 2019-01-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_historicposition_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
