# Generated by Django 2.1.2 on 2018-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_disallowedusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.IntegerField(default=0),
        ),
    ]
