# Generated by Django 2.1.2 on 2018-12-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181129_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('reward', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DisallowedUsername',
        ),
        migrations.AddField(
            model_name='account',
            name='distance_traveled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='notification_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='coins',
            field=models.IntegerField(default=100),
        ),
    ]
