version: '3.7'

services:
  django:
    build:
      dockerfile: docker/development/Dockerfile
    volumes:
      - ../api:/code

  site:
    restart: always
    build:
      dockerfile: docker/development/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../site:/code

  celery:
    build:
      dockerfile: docker/development/Dockerfile

  celery-beat:
    build:
      dockerfile: docker/development/Dockerfile
