version: '3.7'

services:
  django:
    build:
      context: ../api
      dockerfile: docker/production/Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - assets:/code/assets
      - static:/code/static
      - ./media:/media
      - ./config:/code/config
      - site_build:/code/site_build
    links:
      - broker
    env_file:
      - ./config/keys.env
    environment:
        - CELERY_BROKER=amqp://guest:guest@broker:5672
    depends_on:
      - postgres
      - broker
      - site

  site:
    build:
      context: ../site
      dockerfile: docker/production/Dockerfile
    volumes:
      - site_build:/code/build
    env_file:
      - ./config/keys.env

  postgres:
    image: mdillon/postgis
    ports:
      - "5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - ./config/keys.env

  broker:
    hostname: broker
    image: rabbitmq:latest
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - 5672:5672

  worker:
    build:
      context: ../api
      dockerfile: docker/production/Dockerfile
    restart: "no"
    command: celery -A api worker -l info
    links:
      - broker
    depends_on:
      - broker

volumes:
    assets:
    static:
    site_build:
