# Generated by Django 2.1.2 on 2019-01-14 13:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_auto_20190114_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified', models.BooleanField(default=False)),
                ('click_through', models.BooleanField(default=False)),
                ('click_through_timestamp', models.DateTimeField(blank=True, null=True)),
                ('did_complete', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='RadarIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(default='', max_length=80)),
                ('short', models.CharField(default='', max_length=37)),
                ('body', models.TextField(blank=True, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('radius', models.IntegerField(blank=True, null=True)),
                ('do_notify', models.BooleanField(default=True)),
                ('end_date', models.DateTimeField()),
                ('issued_for', models.CharField(default='', max_length=200)),
                ('hits', models.ManyToManyField(to='business.RadarHit')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account')),
            ],
        ),
    ]
