# Generated by Django 2.1.2 on 2018-11-08 18:16

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('google_token', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_token', models.CharField(blank=True, max_length=100, null=True)),
                ('signup_complete', models.BooleanField(default=False)),
                ('sigPos', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('avatar', models.IntegerField(default=1)),
                ('coins', models.IntegerField(default=0)),
                ('blocked', models.BooleanField(default=False)),
                ('userNote', models.TextField(blank=True, null=True)),
                ('userLink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
