# Generated by Django 2.1.2 on 2018-12-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0002_auto_20181111_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordfilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
