# Generated by Django 2.1.2 on 2018-11-08 18:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('msg', 'msg'), ('deal', 'deal'), ('review', 'review'), ('warn', 'warn')], max_length=12)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('visits', models.IntegerField(default=0)),
                ('created_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='reports',
            field=models.ManyToManyField(to='clouds.Report'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='votes',
            field=models.ManyToManyField(to='clouds.Vote'),
        ),
        migrations.AddField(
            model_name='cloud',
            name='messages',
            field=models.ManyToManyField(to='clouds.Message'),
        ),
    ]
