# Generated by Django 2.1.2 on 2018-12-04 19:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('chat', 'chat'), ('deal', 'deal'), ('review', 'review'), ('countdown', 'countdown')], max_length=12)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('body', models.TextField()),
                ('code', models.CharField(blank=True, max_length=20)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('expiry', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.AddField(
            model_name='cloud',
            name='reports',
            field=models.ManyToManyField(blank=True, to='clouds.Report'),
        ),
        migrations.AddField(
            model_name='cloud',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='cloud',
            name='votes',
            field=models.ManyToManyField(blank=True, to='clouds.Vote'),
        ),
    ]
