# Generated by Django 2.1.2 on 2018-11-11 11:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='message',
            name='reports',
            field=models.ManyToManyField(blank=True, to='clouds.Report'),
        ),
        migrations.AlterField(
            model_name='message',
            name='votes',
            field=models.ManyToManyField(blank=True, to='clouds.Vote'),
        ),
    ]
