# Generated by Django 2.1.2 on 2018-11-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0003_auto_20181111_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloud',
            name='created_timestamp',
        ),
    ]
