# Generated by Django 2.1.2 on 2018-11-13 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0004_remove_cloud_created_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
