# Generated by Django 2.1.2 on 2018-11-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0005_cloud_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
