# Generated by Django 2.1.2 on 2018-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0006_auto_20181114_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='cast',
        ),
        migrations.AddField(
            model_name='vote',
            name='type',
            field=models.CharField(choices=[('up', 'up'), ('down', 'down')], default='up', max_length=12),
            preserve_default=False,
        ),
    ]
