# Generated by Django 2.1.2 on 2018-11-14 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0007_auto_20181114_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
