# Generated by Django 2.1.2 on 2018-11-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0010_auto_20181116_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='votes',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='created_timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='cloud',
            old_name='created_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='cloud',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='cloud',
            name='visits',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='type',
        ),
        migrations.AddField(
            model_name='cloud',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloud',
            name='reports',
            field=models.ManyToManyField(blank=True, to='clouds.Report'),
        ),
        migrations.AddField(
            model_name='cloud',
            name='votes',
            field=models.ManyToManyField(blank=True, to='clouds.Vote'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
