# Generated by Django 2.1.2 on 2018-11-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0011_auto_20181125_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cloud',
            name='expiry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloud',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloud',
            name='type',
            field=models.CharField(choices=[('chat', 'chat'), ('deal', 'deal'), ('review', 'review'), ('countdown', 'countdown')], max_length=12),
        ),
    ]
